"""Deterministic local LLM for dev without API keys."""

from __future__ import annotations

import json
import re

from rag_project.schemas.generation import CitedClaim, GeneratedAnswer
from rag_project.schemas.retrieval import RetrievalCandidate


class LocalStubLLM:
    def generate_grounded(
        self,
        query: str,
        candidates: list[RetrievalCandidate],
        citation_map: dict[str, str],
    ) -> GeneratedAnswer:
        if not candidates:
            return GeneratedAnswer(
                answer="I don't have enough reliable information in the indexed documents to answer this confidently.",
                abstained=True,
                abstention_reason="No context",
                confidence_score=0.0,
            )
        best = candidates[0]
        q_lower = query.lower()
        # Simple keyword matching for refund policy etc.
        if "refund" in q_lower and "refund" in best.text.lower():
            claim = "Refunds are available within 30 days with receipt per store policy."
            for c in candidates:
                if "30" in c.text or "refund" in c.text.lower():
                    best = c
                    break
            cid = citation_map.get(best.chunk_id, "C1")
            return GeneratedAnswer(
                answer=f"Based on indexed documents: {best.text[:400]}",
                cited_claims=[CitedClaim(claim=claim, citations=[cid])],
                confidence_score=0.82,
                limitations=["Generated by local stub LLM"],
            )
        # Default grounded excerpt
        cid = citation_map.get(best.chunk_id, "C1")
        excerpt = best.text[:300].strip()
        return GeneratedAnswer(
            answer=f"Based on the retrieved document: {excerpt}",
            cited_claims=[CitedClaim(claim=excerpt[:200], citations=[cid])],
            confidence_score=0.65,
            limitations=["Local stub - verify with production LLM"],
        )
